// Mock 데이터 - 로그인 테스트용 최소 데이터
export const mockAdminUser = {
  id: 1,
  name: "관리자",
  email: "admin@hotel.com",
  role: "admin",
};

export const mockHotels = [
  {
    id: 1,
    name: "서울 시티 호텔",
    brand: "CityLine",
    partnerName: "홍길동",
    region: "서울",
    city: "서울",
    roomCount: 120,
    averagePrice: 160000,
    status: "active",
    approvalStatus: "pending",
    createdAt: "2024-01-05",
  },
  {
    id: 2,
    name: "제주 오션 리조트",
    brand: "OceanStay",
    partnerName: "김바다",
    region: "제주",
    city: "제주",
    roomCount: 80,
    averagePrice: 220000,
    status: "inactive",
    approvalStatus: "pending",
    createdAt: "2024-02-12",
  },
  {
    id: 3,
    name: "부산 마린 호텔",
    brand: "Marine",
    partnerName: "박해운",
    region: "부산",
    city: "부산",
    roomCount: 150,
    averagePrice: 180000,
    status: "active",
    approvalStatus: "pending",
    createdAt: "2024-03-18",
  },
  {
    id: 4,
    name: "강릉 포레스트 빌라",
    brand: "Forest",
    partnerName: "이솔",
    region: "강원",
    city: "강릉",
    roomCount: 60,
    averagePrice: 140000,
    status: "active",
    approvalStatus: "approved",
    createdAt: "2024-04-22",
  },
  {
    id: 5,
    name: "대구 센트럴 호텔",
    brand: "Central",
    partnerName: "최중심",
    region: "대구",
    city: "대구",
    roomCount: 95,
    averagePrice: 130000,
    status: "inactive",
    approvalStatus: "rejected",
    createdAt: "2024-05-10",
  },
];

export const mockBookings = [
  {
    id: "BK-2024001",
    code: "BK-2024001",
    hotelName: "서울 시티 호텔",
    roomType: "디럭스",
    guestName: "김철수",
    guestEmail: "kim@example.com",
    checkIn: "2024-06-10",
    checkOut: "2024-06-12",
    totalAmount: 320000,
    status: "confirmed",
    paymentStatus: "paid",
  },
  {
    id: "BK-2024002",
    code: "BK-2024002",
    hotelName: "제주 오션 리조트",
    roomType: "스위트",
    guestName: "이영희",
    guestEmail: "lee@example.com",
    checkIn: "2024-06-15",
    checkOut: "2024-06-18",
    totalAmount: 660000,
    status: "pending",
    paymentStatus: "pending",
  },
  {
    id: "BK-2024003",
    code: "BK-2024003",
    hotelName: "부산 마린 호텔",
    roomType: "패밀리",
    guestName: "박민수",
    guestEmail: "park@example.com",
    checkIn: "2024-07-01",
    checkOut: "2024-07-03",
    totalAmount: 420000,
    status: "completed",
    paymentStatus: "paid",
  },
  {
    id: "BK-2024004",
    code: "BK-2024004",
    hotelName: "강릉 포레스트 빌라",
    roomType: "스탠다드",
    guestName: "정하늘",
    guestEmail: "jung@example.com",
    checkIn: "2024-06-20",
    checkOut: "2024-06-22",
    totalAmount: 280000,
    status: "cancelled",
    paymentStatus: "refunded",
  },
  {
    id: "BK-2024005",
    code: "BK-2024005",
    hotelName: "대구 센트럴 호텔",
    roomType: "비즈니스",
    guestName: "오세훈",
    guestEmail: "oh@example.com",
    checkIn: "2024-07-05",
    checkOut: "2024-07-06",
    totalAmount: 150000,
    status: "confirmed",
    paymentStatus: "paid",
  },
];

export const mockUsers = [
  {
    id: 1,
    name: "김철수",
    email: "kim@example.com",
    phone: "010-1234-5678",
    role: "user",
    type: "user",
    level: "gold",
    status: "active",
    createdAt: "2023-11-10",
  },
  {
    id: 2,
    name: "이영희",
    email: "lee@example.com",
    phone: "010-2345-6789",
    role: "host",
    type: "host",
    level: "silver",
    status: "inactive",
    createdAt: "2023-12-02",
  },
  {
    id: 3,
    name: "박민수",
    email: "park@example.com",
    phone: "010-3456-7890",
    role: "user",
    type: "user",
    level: "vip",
    status: "suspended",
    createdAt: "2024-01-15",
  },
  {
    id: 4,
    name: "최수현",
    email: "choi@example.com",
    phone: "010-4567-8901",
    role: "admin",
    type: "admin",
    level: "gold",
    status: "active",
    createdAt: "2023-10-08",
  },
  {
    id: 5,
    name: "정하늘",
    email: "jung@example.com",
    phone: "010-5678-9012",
    role: "user",
    type: "user",
    level: "bronze",
    status: "active",
    createdAt: "2024-02-20",
  },
];

export const mockReviews = [
  {
    id: 101,
    hotelName: "서울 시티 호텔",
    content: "위치가 좋아서 이동하기 편했습니다.",
    title: "만족스러운 숙박",
    guestName: "김철수",
    guestEmail: "kim@example.com",
    rating: 4.5,
    reportCount: 1,
    reportStatus: "reported",
    status: "published",
    createdAt: "2024-05-12",
  },
  {
    id: 102,
    hotelName: "제주 오션 리조트",
    content: "뷰가 좋았지만 시설이 조금 오래되었습니다.",
    title: "아쉬운 부분 있음",
    guestName: "이영희",
    guestEmail: "lee@example.com",
    rating: 3.0,
    reportCount: 2,
    reportStatus: "reported",
    status: "reported",
    createdAt: "2024-05-18",
  },
  {
    id: 103,
    hotelName: "부산 마린 호텔",
    content: "직원 서비스가 매우 친절했어요.",
    title: "친절한 서비스",
    guestName: "박민수",
    guestEmail: "park@example.com",
    rating: 5,
    reportCount: 3,
    reportStatus: "reported",
    status: "published",
    createdAt: "2024-05-25",
  },
  {
    id: 104,
    hotelName: "강릉 포레스트 빌라",
    content: "청결 상태가 조금 아쉬웠습니다.",
    title: "청결 개선 필요",
    guestName: "정하늘",
    guestEmail: "jung@example.com",
    rating: 2.5,
    reportCount: 1,
    reportStatus: "reported",
    status: "hidden",
    createdAt: "2024-06-01",
  },
  {
    id: 105,
    hotelName: "대구 센트럴 호텔",
    content: "비즈니스 출장에 적합한 호텔입니다.",
    title: "출장에 최적",
    guestName: "오세훈",
    guestEmail: "oh@example.com",
    rating: 4.0,
    reportCount: 0,
    reportStatus: "clean",
    status: "published",
    createdAt: "2024-06-05",
  },
];

export const mockCoupons = [
  {
    id: 1,
    name: "여름 특가 10%",
    description: "여름 시즌 한정 10% 할인",
    code: "SUMMER10",
    type: "percent",
    discountValue: 10,
    minOrderAmount: 100000,
    startDate: "2024-06-01",
    endDate: "2024-08-31",
    usageCount: 120,
    usageLimit: 500,
    status: "active",
  },
  {
    id: 2,
    name: "신규 회원 2만원",
    description: "첫 예약 시 2만원 할인",
    code: "WELCOME20",
    type: "amount",
    discountValue: 20000,
    minOrderAmount: 150000,
    startDate: "2024-01-01",
    endDate: "2024-12-31",
    usageCount: 80,
    usageLimit: 1000,
    status: "active",
  },
  {
    id: 3,
    name: "주중 할인 15%",
    description: "주중 예약 시 15% 할인",
    code: "WEEKDAY15",
    type: "percent",
    discountValue: 15,
    minOrderAmount: 80000,
    startDate: "2024-05-01",
    endDate: "2024-07-31",
    usageCount: 45,
    usageLimit: 200,
    status: "scheduled",
  },
  {
    id: 4,
    name: "블랙프라이데이 5만원",
    description: "한정 기간 5만원 할인",
    code: "BLACK50",
    type: "amount",
    discountValue: 50000,
    minOrderAmount: 200000,
    startDate: "2023-11-15",
    endDate: "2023-12-05",
    usageCount: 300,
    usageLimit: 300,
    status: "expired",
  },
  {
    id: 5,
    name: "테스트 중단 쿠폰",
    description: "내부 테스트용",
    code: "PAUSE30",
    type: "percent",
    discountValue: 30,
    minOrderAmount: 50000,
    startDate: "2024-06-01",
    endDate: "2024-12-31",
    usageCount: 10,
    usageLimit: 100,
    status: "paused",
  },
];

export const mockDashboardStats = {
  todayBookings: 15,
  totalRevenue: 12500000,
  activeHotels: 45,
  newUsers: 8,
  chartData: {
    labels: ["1월", "2월", "3월", "4월", "5월", "6월"],
    revenue: [2000000, 2500000, 2200000, 2800000, 3000000, 3200000],
    bookings: [45, 58, 52, 67, 72, 78],
  },
  recentBookings: mockBookings.slice(0, 5),
  recentUsers: mockUsers.slice(0, 5),
  recentReviews: mockReviews.slice(0, 5),
};
